#!/usr/bin/env sh

if [ $# -lt 1 ]; then
  echo "Error: Please pass filepath"
  exit
fi

TARGET=$(realpath $1)
shift

if [ ! -f $TARGET ]; then
  echo "Error: File \"$TARGET\" does not exists"
  exit
fi

qemu-ppc -g 8888 $TARGET $@ 2> /dev/null &
gdb-multiarch --command=/entry/ppcinit --se=$TARGET
